# Generated by Django 5.0.1 on 2024-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_link',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='source_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
