# Generated by Django 5.0.1 on 2024-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_source_link_news_source_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
